routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect('login');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

// namespace -> Admin
Route::group(['middleware' => ['auth','secretary'], 'namespace' => 'Admin', 'prefix' => 'admin'], function (){
    // Admin->teachers
    Route::get('teachers', 'TeacherController@index');
    Route::get('teachers/create', 'TeacherController@create');
    Route::post('teachers/create', 'TeacherController@store');
    Route::get('teachers/{id}/edit', 'TeacherController@edit');
    Route::post('teachers/{id}/edit', 'TeacherController@update');
    Route::get('teachers/{id}/delete', 'TeacherController@delete');
    // Admin->postulants
    Route::get('postulants', 'PostulantController@index');
    Route::get('postulants/create', 'PostulantController@create');
    Route::post('postulants/create', 'PostulantController@store');
    Route::get('postulants/{id}/edit', 'PostulantController@edit');
    Route::post('postulants/{id}/edit', 'PostulantController@update');
    Route::get('postulants/{id}/delete', 'PostulantController@delete');
    // Admin->semesters
    Route::get('semesters', 'SemesterController@index');
    Route::get('semesters/create', 'SemesterController@create');
    Route::post('semesters/create', 'SemesterController@store');
    Route::get('semesters/{id}/edit', 'SemesterController@edit');
    Route::post('semesters/{id}/edit', 'SemesterController@update');
    Route::get('semesters/{id}/delete', 'SemesterController@delete');
    // Admin->careers
    Route::get('careers', 'CareerController@index');
    Route::get('careers/create', 'CareerController@create');
    Route::post('careers/create', 'CareerController@store');
    Route::get('careers/{id}/edit', 'CareerController@edit');
    Route::post('careers/{id}/edit', 'CareerController@update');
    Route::get('careers/{id}/delete', 'CareerController@delete');
    Route::get('careers/{id}/modules', 'CareerController@modules');

    // Admin->modules
    Route::get('modules', 'ModuleController@index');
    Route::get('modules/create', 'ModuleController@create');
    Route::post('modules/create', 'ModuleController@store');
    Route::get('modules/{id}/edit', 'ModuleController@edit');
    Route::post('modules/{id}/edit', 'ModuleController@update');
    Route::get('modules/{id}/delete', 'ModuleController@delete');

    // Admin->courses
    Route::get('courses', 'CourseController@index');
    Route::get('courses/create', 'CourseController@create');
    Route::post('courses/create', 'CourseController@store');
    Route::get('courses/{id}/edit', 'CourseController@edit');
    Route::post('courses/{id}/edit', 'CourseController@update');
    Route::get('courses/{id}/delete', 'CourseController@delete');
    // Admin->workload
    Route::get('workload', 'WorkloadController@index');
    Route::get('workload/create', 'WorkloadController@create');
    Route::post('workload/create', 'WorkloadController@store');
    Route::get('workload/{id}/edit', 'WorkloadController@edit');
    Route::post('workload/{id}/edit', 'WorkloadController@update');
    Route::get('workload/{id}/delete', 'WorkloadController@delete');
    // Admin->enrollment
    Route::get('enrollments', 'EnrollmentController@index');
    Route::get('enrollments/create', 'EnrollmentController@create');
    Route::post('enrollments/create', 'EnrollmentController@store');
    Route::get('enrollments/{id}/edit', 'EnrollmentController@edit');
    Route::post('enrollments/{id}/edit', 'EnrollmentController@update');
    Route::get('enrollments/{id}/delete', 'EnrollmentController@delete');

    Route::group(['namespace' => 'Reports','prefix' => 'reports'], function (){
        Route::get('enrollments', 'EnrollmentController@index');
    });

    Route::get('graphics', 'GraphicController@index');
});

Route::group(['middleware' => ['auth','teacher'], 'namespace' => 'Admin', 'prefix' => 'admin'], function () {
    // teacher->assistance
    Route::get('/assistances', 'AssistanceController@index');
    Route::get('/assistances/create', 'AssistanceController@create');
    Route::post('/assistances/create', 'AssistanceController@store');
    Route::get('/assistances/{id}/edit', 'AssistanceController@edit');
    Route::post('/assistances/{id}/edit', 'AssistanceController@update');
    Route::get('/assistances/{id}/delete', 'AssistanceController@delete');
    // teacher->notes
    Route::get('/notes', 'NoteController@index');
    Route::get('/notes/create', 'NoteController@create');
    Route::post('/notes/create', 'NoteController@store');
    Route::get('/notes/{id}/edit', 'NoteController@edit');
    Route::post('/notes/{id}/edit', 'NoteController@update');
    Route::get('/notes/{id}/delete', 'NoteController@delete');
    Route::group(['namespace' => 'Reports','prefix' => 'reports'], function (){
        Route::get('assistances', 'AssistanceController@index');
        Route::get('notes', 'NoteController@index');
    });
});

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    protected $fillable = [
        'first_name', 'last_name', 'email', 'password', 'role',
    ];
    protected $hidden = [
        'password', 'remember_token',
    ];

    protected  $appends = ['name_complete', 'code'];

    //relationship
    public function career()
    {
        return $this->belongsTo(Career::class);
    }

    public function workload_careers()
    {
        return $this->belongsToMany(Career::class, 'workloads', 'teacher_id', 'career_id')->distinct('id');

    }

    public function assistances()
    {
        return $this->hasMany(Assistance::class);
    }

    public function enrollments()
    {
        return $this->hasMany(Enrollment::class, 'postulant_id');
    }

    public function notes()
    {
        return $this->hasMany(Note::class);
    }

    //accessors
    public function getGenderNameAttribute() // accessor gender_name
    {
        if ($this->gender == 'M')
            return 'Masculino';
        if ($this->gender == 'F')
            return 'Femenino';

        return ''; // ?
    }

    public function getImageUrlAttribute()
    {
        if($this->image)
            return '/images/users/'.$this->image;
        else
            return '/images/users/avatar-1.jpg';
    }

    public function getIsAdminAttribute()
    {
        return $this->role == 0 || $this->role == 1;
    }

    public function getIsSecretaryAttribute()
    {
        return $this->role == 2;
    }

    public function getIsTeacherAttribute()
    {
        return $this->role == 3;
    }

    public function getNameCompleteAttribute()
    {
        return $this->first_name.' '.$this->last_name;
    }

    public  function getCodeAttribute()
    {
        $firstEnrollment = $this->enrollments()->first();
        if ($firstEnrollment)
            return $firstEnrollment->code;

        return null;
    }
}

app/Http/Controllers/Admin/PostulantController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Career;
use App\User;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\File;

class PostulantController extends Controller
{
    public function index()
    {
        $postulants = User::where('role', 4)->get();
        return view('admin.postulants.index', compact('postulants'));
    }

    public function create()
    {
        $careers = Career::orderBy('name', 'asc')->get();
        return view('admin.postulants.create', compact('careers'));
    }

    public function store(Request $request)
    {
        $rules = [
            'dni' => 'required',
            'gender' => 'required',
            'first_name' => 'required|regex:/^[A-Za-z áéíóúÁÉÍÓÚ]+$/|max:255',
            'last_name' => 'required|regex:/^[A-Za-z áéíóúÁÉÍÓÚ]+$/|max:255',
            'career_id' => 'required',
            'email' => 'required|email|max:255|unique:users',
            'password' => 'required|min:6'
        ];
        $messages = [
            'dni.required' => 'Es necesario ingresar el dni.',
            'gender.required' => 'Es necesario ingresar el género.',
            'first_name.required' => 'Es indispensable ingresar el nombre.',
            'first_name.regex' => 'Ingrese nombres válidos',
            'first_name.max' => 'El nombre ingresado es demasiado extenso.',
            'last_name.required' => 'Es indispensable ingresar los apellidos.',
            'last_name.regex' => 'Ingrese apellidos válidos',
            'last_name.max' => 'Los apellidos ingresados son demasiado extenso.',
            'career_id.required' => 'Es indispensable seleccionar la carrera.',
            'email.required' => 'Es indispensable ingresar el e-mail.',
            'email.email' => 'El e-mail ingresado no es válido.',
            'email.max' => 'El e-mail es demasiado extenso.',
            'email.unique' => 'El e-mail ya se encuentra en uso.',
            'password.required' => 'Es necesario ingresar una contraseña',
            'password.min' => 'La contraseña debe presentar al menos 6 caracteres.',
        ];

        $this->validate($request, $rules, $messages);

        $postulant = new User();
        $postulant->first_name = $request->first_name;
        $postulant->last_name = $request->last_name;
        $postulant->gender = $request->gender;
        $postulant->dni = $request->dni;
        $postulant->address = $request->address;
        $postulant->career_id = $request->career_id;
        $postulant->phone = $request->phone;
        $postulant->cellphone = $request->cellphone;
        if ($request->hasFile('image')) {
            $postulantImage = $request->file('image');
            $name = uniqid().'.'.$postulantImage->getClientOriginalExtension();
            $path = public_path().'/images/users';
            $postulantImage->move($path, $name);

            $postulant->image = $name;
        }
        $postulant->email = $request->email;
        $postulant->password = bcrypt($request->password);
        $postulant->role = 4;
        $postulant->save();

        return redirect('/admin/postulants')->with('notification', 'Se registró correctamente');
    }

    public function edit($id)
    {
        $postulant = User::find($id);
        $careers = Career::orderBy('name', 'asc')->get();

        return view('admin.postulants.edit', compact('postulant', 'careers'));
    }

    public function update($id, Request $request)
    {
        $rules = [
            'dni' => 'required',
            'gender' => 'required',
            'first_name' => 'required|regex:/^[A-Za-z áéíóúÁÉÍÓÚ]+$/|max:255',
            'last_name' => 'required|regex:/^[A-Za-z áéíóúÁÉÍÓÚ]+$/|max:255',
            'career_id' => 'required',
            'email' => "required|email|max:255|unique:users,email,$id",
            'password' => 'nullable|min:6'
        ];
        $messages = [
            'dni.required' => 'Es necesario ingresar el dni.',
            'gender.required' => 'Es necesario ingresar el género.',
            'first_name.required' => 'Es indispensable ingresar el nombre.',
            'first_name.regex' => 'Ingrese nombres válidos',
            'first_name.max' => 'El nombre ingresado es demasiado extenso.',
            'last_name.required' => 'Es indispensable ingresar los apellidos.',
            'last_name.regex' => 'Ingrese apellidos válidos',
            'last_name.max' => 'Los apellidos ingresados son demasiado extenso.',
            'career_id.required' => 'Es indispensable seleccionar la carrera.',
            'email.required' => 'Es indispensable ingresar el e-mail.',
            'email.email' => 'El e-mail ingresado no es válido.',
            'email.max' => 'El e-mail es demasiado extenso.',
            'email.unique' => 'El e-mail ya se encuentra en uso.',
            'password.min' => 'La contraseña debe presentar al menos 6 caracteres.',
        ];

        $this->validate($request, $rules, $messages);

        $postulant = User::find($id);
        $postulant->first_name = $request->first_name;
        $postulant->last_name = $request->last_name;
        $postulant->gender = $request->gender;
        $postulant->dni = $request->dni;
        $postulant->address = $request->address;
        $postulant->career_id = $request->career_id;
        $postulant->phone = $request->phone;
        $postulant->cellphone = $request->cellphone;
        if ($request->hasFile('image')) {
            $pathDelete = public_path('/images/users/' . $postulant->image);
            File::delete($pathDelete);

            $postulantImage = $request->file('image');
            $name = uniqid().'.'.$postulantImage->getClientOriginalExtension();
            $path = public_path().'/images/users';
            $postulantImage->move($path, $name);

            $postulant->image = $name;
        }
        $postulant->email = $request->email;
        if($request->password)
            $postulant->password = bcrypt($request->password);

        $postulant->save();

        return redirect('admin/postulants')->with('notification', 'Se guardó los cambios correctamente');
    }

    public function delete($id)
    {
        User::find($id)->delete();

        return back()->with('notification', 'Se eliminó correctamente.');
    }
}

app/Http/Controllers/Api/PostulantController.php
<?php

namespace App\Http\Controllers\Api;

use App\Course;
use App\Enrollment;
use App\Semester;
use App\User;
use App\Workload;
use Carbon\Carbon;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\DB;

class PostulantController extends Controller
{
    public function show(Request $request)
    {
        $queryText = $request->input('queryText');

        if ($queryText)
            return User::where('role', 4)->where(function ($query) use ($queryText) {
                $query->where('first_name', 'like', "%$queryText%")
                    ->orWhere('last_name', 'like', "%$queryText%");
            })->select('id', DB::raw('CONCAT(first_name," ",last_name) as text'))->get();
        else
            return User::where('role', 4)->orderBy('first_name')->take(20)
                ->select('id', DB::raw('CONCAT(first_name," ",last_name) as text'))->get();
    }

    public function enrollment($career_id, $courseId, Request $request)
    {
        $date = $request->date;
        $course = Course::find($courseId);
        $dateCarbon = Carbon::createFromFormat('d/m/Y', $date);

        $semester = Semester::where('start_date', '<', $dateCarbon)->where('end_date', '>', $dateCarbon)->first();

        if (!$semester)
            return '';

        // $enrollments
        return Enrollment::with('postulant')->where('career_id', $career_id)
            ->where('cycle', $course->cycle)->where('semester_id', $semester->id)->get();
    }
}

resources/views/admin/postulants/create.blade.php
@extends('layouts.app')

@section('page-title')
    <a href="{{ url('/admin/postulants') }}">Postulantes</a> >
    Nuevo
@endsection
@section('styles')
    <link href="{{ asset('plugins/timepicker/bootstrap-timepicker.min.css') }}" rel="stylesheet">
    <link href="{{ asset('plugins/bootstrap-datepicker/dist/css/bootstrap-datepicker.min.css') }}" rel="stylesheet">

    <link href="{{ asset('plugins/fileuploads/css/dropify.min.css') }}"/>
@endsection
@section('content')
    <!-- Start content -->
    <div class="content">
        <div class="container">
            @include('includes.alerts')
            <form role="form"  action="" method="POST">
                @csrf
                <div class="card-box">
                    <div class="row">
                        <div class="col-md-6">
                            <h4 class="m-t-0 header-title m-t-0 m-b-20"><b>Datos del postulante</b></h4>
                            <div class="row">
                                <div class="col-sm-6">
                                    <div class="form-group">
                                        <label for="dni" class="control-label">DNI</label>
                                        <input type="text" placeholder="" data-mask="99999999" class="form-control" id="dni" name="dni" value="{{ old('dni') }}">
                                    </div>
                                </div>
                                <div class="col-sm-6">
                                    <p class="control-label font-600">Género</p>
                                    <div class="radio radio-inline">
                                        <input type="radio" id="man" value="M" name="gender" {{ old('gender') == 'M' ? 'checked' : '' }}>
                                        <label for="man"> Masculino </label>
                                    </div>
                                    <div class="radio radio-purple radio-inline">
                                        <input type="radio" id="woman" value="F" name="gender" {{ old('gender') == 'F' ? 'checked' : '' }}>
                                        <label for="woman"> Femenino </label>
                                    </div>
                                </div>
                                <div class="clearfix"></div>
                                <div class="col-sm-6">
                                    <div class="form-group">
                                        <label for="first_name" class="control-label">Nombre(s)</label>
                                        <input type="text" class="form-control" id="first_name" placeholder="Ingresar nombre" name="first_name" value="{{ old('first_name') }}">
                                    </div>
                                </div>
                                <div class="col-sm-6">
                                    <div class="form-group">
                                        <label for="last_name" class="control-label">Apellidos</label>
                                        <input type="text" class="form-control" id="last_name" name="last_name" placeholder="Ingresar apellidos" value="{{ old('last_name') }}">
                                    </div>
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="address" class="control-label">Dirección</label>
                                <input type="text" class="form-control" id="address" name="address" placeholder="Ingresar dirección" value="{{ old('address') }}">
                            </div>
                            <div class="row">
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label for="phone" class="control-label">Teléfono Fijo</label>
                                        <input type="text" placeholder="" data-mask="999 999" class="form-control" id="phone" name="phone" value="{{ old('phone') }}">
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label for="cellphone" class="control-label">Teléfono Móvil</label>
                                        <input type="text" placeholder="" data-mask="999 999 999" class="form-control" id="cellphone" name="cellphone" value="{{ old('cellphone') }}">
                                    </div>
                                </div>
                            </div>
                        </div><!-- end col -->
                        <div class="col-md-6">
                            <div class="form-group m-t-15">
                                <label for="career_id" class="control-label">Carrera</label>
                                <select class="form-control" name="career_id">
                                    <option value="">Seleccione carrera</option>
                                    @foreach($careers as $career)
                                        <option value="{{ $career->id }}" {{ old('career_id') == $career->id ? 'selected' : ''  }}>{{ $career->name }}</option>
                                    @endforeach
                                </select>
                            </div>
                            <div class="form-group">
                                <label for="email" class="control-label">Email</label>
                                <input type="text" class="form-control" id="email" name="email" placeholder="Ingresar email" value="{{ old('email') }}">
                            </div>
                            <div class="form-group">
                                <label for="password" class="control-label">Contraseña</label>
                                <input type="password" class="form-control" id="password" name="password" placeholder="" value="{{ old('password') }}">
                            </div>
                            <div class="form-group m-t-20">
                                <label for="image">Imagen</label>
                                <input id="image" type="file" name="image" class="dropify" data-height="150"/>
                            </div>
                        </div><!-- end row -->
                        <div class="col-sm-12">
                            <div class="form-group">
                                <button class="btn btn-primary btn-bordred m-t-30">
                                    Registrar
                                </button>
                                <a href="{{ url('admin/postulants') }}" class="btn btn-default btn-bordred m-t-30">
                                    Cancelar
                                </a>
                            </div>
                        </div>
                    </div><!-- end col -->
                </div>
            </form>
        </div> <!-- container -->
    </div> <!-- content -->
@endsection
@section('scripts')
    <script src="{{ asset('plugins/fileuploads/js/dropify.min.js') }}"></script>
    <script>
        $('.dropify').dropify({
            messages: {
                'default': 'Drag and drop a file here or click',
                'replace': 'Drag and drop or click to replace',
                'remove': 'Remove',
                'error': 'Ooops, something wrong appended.'
            },
            error: {
                'fileSize': 'The file size is too big (1M max).'
            }
        });
    </script>
    <script src="{{ asset('plugins/timepicker/bootstrap-timepicker.min.js') }}"></script>
    <script src="{{ asset('plugins/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js') }}"></script>
    <script>
        jQuery('#datepicker-autoclose').datepicker({
            autoclose: true,
            todayHighlight: true
        });
    </script>
@endsection

resources/views/admin/postulants/edit.blade.php
@extends('layouts.app')

@section('page-title')
    <a href="{{ url('/admin/postulants') }}">Postulantes</a> >
    Nuevo
@endsection
@section('styles')
    <link href="{{ asset('plugins/timepicker/bootstrap-timepicker.min.css') }}" rel="stylesheet">
    <link href="{{ asset('plugins/bootstrap-datepicker/dist/css/bootstrap-datepicker.min.css') }}" rel="stylesheet">

    <link href="{{ asset('plugins/fileuploads/css/dropify.min.css') }}"/>
@endsection
@section('content')
    <!-- Start content -->
    <div class="content">
        <div class="container">
            @include('includes.alerts')
            <form role="form"  action="" method="POST" enctype="multipart/form-data">
                @csrf
                <div class="card-box">
                    <div class="row">
                        <div class="col-md-6">
                            <h4 class="m-t-0 header-title m-t-0 m-b-20"><b>Datos del docente</b></h4>
                            <div class="row">
                                <div class="col-sm-6">
                                    <div class="form-group">
                                        <label for="dni" class="control-label">DNI</label>
                                        <input type="text" placeholder="" data-mask="99999999" class="form-control" id="dni" name="dni" value="{{ $postulant->dni }}">
                                    </div>
                                </div>
                                <div class="col-sm-6">
                                    <p class="control-label font-600">Género</p>
                                    <div class="radio radio-inline">
                                        <input type="radio" id="man" value="M" name="gender" {{ $postulant->gender == 'M' ? 'checked' : '' }}>
                                        <label for="man"> Masculino </label>
                                    </div>
                                    <div class="radio radio-purple radio-inline">
                                        <input type="radio" id="woman" value="F" name="gender" {{ $postulant->gender == 'F' ? 'checked' : '' }}>
                                        <label for="woman"> Femenino </label>
                                    </div>
                                </div>
                                <div class="clearfix"></div>
                                <div class="col-sm-6">
                                    <div class="form-group">
                                        <label for="first_name" class="control-label">Nombre(s)</label>
                                        <input type="text" class="form-control" id="first_name" name="first_name" placeholder="Ingresar nombre" value="{{$postulant->first_name }}">
                                    </div>
                                </div>
                                <div class="col-sm-6">
                                    <div class="form-group">
                                        <label for="last_name" class="control-label">Apellidos</label>
                                        <input type="text" class="form-control" id="last_name" name="last_name" placeholder="Ingresar apellidos" value="{{ $postulant->last_name }}">
                                    </div>
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="address" class="control-label">Dirección</label>
                                <input type="text" class="form-control" id="address" name="address" placeholder="Ingresar dirección" value="{{ $postulant->address }}">
                            </div>
                            <div class="row">
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label for="phone" class="control-label">Teléfono Fijo</label>
                                        <input type="text" placeholder="" data-mask="999 999" class="form-control" id="phone" name="phone" value="{{ $postulant->phone }}">
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label for="cellphone" class="control-label">Teléfono Móvil</label>
                                        <input type="text" placeholder="" data-mask="999 999 999" class="form-control" id="cellphone" name="cellphone" value="{{ $postulant->cellphone }}">
                                    </div>
                                </div>
                            </div>
                        </div><!-- end col -->
                        <div class="col-md-6">
                            <div class="form-group m-t-15">
                                <label for="career_id" class="control-label">Carrera</label>
                                <select id="career_id" class="form-control" name="career_id">
                                    <option value="">Seleccione carrera</option>
                                    @foreach($careers as $career)
                                        <option value="{{ $career->id }}" {{ $postulant->career_id == $career->id ? 'selected' : ''  }}>{{ $career->name }}</option>
                                    @endforeach
                                </select>
                            </div>
                            <div class="form-group">
                                <label for="email" class="control-label">Email</label>
                                <input type="text" class="form-control" id="email" name="email" placeholder="Ingresar email" value="{{ $postulant->email }}">
                            </div>
                            <div class="form-group">
                                <label for="password" class="control-label">Contraseña <small>(Ingresar solo si desea modificar)</small></label>
                                <input type="password" class="form-control" id="password" name="password" value="">
                            </div>
                            <div class="form-group m-t-20">
                                <label for="image">Imagen</label>
                                <input id="image" type="file" class="dropify" name="image" data-height="150" data-default-file="{{ $postulant->image_url }}"/>
                            </div>
                        </div><!-- end row -->
                        <div class="col-sm-12">
                            <div class="form-group">
                                <button class="btn btn-success btn-bordred m-t-30">
                                    Guardar cambios
                                    <i class="fa fa-save"></i>
                                </button>
                                <a href="{{ url('admin/postulants') }}" class="btn btn-default btn-bordred m-t-30">
                                    Cancelar
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            </form>
        </div> <!-- container -->
    </div> <!-- content -->
@endsection
@section('scripts')
    <script src="{{ asset('plugins/fileuploads/js/dropify.min.js') }}"></script>
    <script>
        $('.dropify').dropify({
            messages: {
                'default': 'Drag and drop a file here or click',
                'replace': 'Drag and drop or click to replace',
                'remove': 'Remove',
                'error': 'Ooops, something wrong appended.'
            },
            error: {
                'fileSize': 'The file size is too big (1M max).'
            }
        });
    </script>
    <script src="{{ asset('plugins/timepicker/bootstrap-timepicker.min.js') }}"></script>
    <script src="{{ asset('plugins/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js') }}"></script>
    <script>
        jQuery('#datepicker-autoclose').datepicker({
            autoclose: true,
            todayHighlight: true
        });
    </script>
@endsection