routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect('login');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

// namespace -> Admin
Route::group(['middleware' => ['auth','secretary'], 'namespace' => 'Admin', 'prefix' => 'admin'], function (){
    // Admin->teachers
    Route::get('teachers', 'TeacherController@index');
    Route::get('teachers/create', 'TeacherController@create');
    Route::post('teachers/create', 'TeacherController@store');
    Route::get('teachers/{id}/edit', 'TeacherController@edit');
    Route::post('teachers/{id}/edit', 'TeacherController@update');
    Route::get('teachers/{id}/delete', 'TeacherController@delete');
    // Admin->postulants
    Route::get('postulants', 'PostulantController@index');
    Route::get('postulants/create', 'PostulantController@create');
    Route::post('postulants/create', 'PostulantController@store');
    Route::get('postulants/{id}/edit', 'PostulantController@edit');
    Route::post('postulants/{id}/edit', 'PostulantController@update');
    Route::get('postulants/{id}/delete', 'PostulantController@delete');
    // Admin->semesters
    Route::get('semesters', 'SemesterController@index');
    Route::get('semesters/create', 'SemesterController@create');
    Route::post('semesters/create', 'SemesterController@store');
    Route::get('semesters/{id}/edit', 'SemesterController@edit');
    Route::post('semesters/{id}/edit', 'SemesterController@update');
    Route::get('semesters/{id}/delete', 'SemesterController@delete');
    // Admin->careers
    Route::get('careers', 'CareerController@index');
    Route::get('careers/create', 'CareerController@create');
    Route::post('careers/create', 'CareerController@store');
    Route::get('careers/{id}/edit', 'CareerController@edit');
    Route::post('careers/{id}/edit', 'CareerController@update');
    Route::get('careers/{id}/delete', 'CareerController@delete');
    Route::get('careers/{id}/modules', 'CareerController@modules');

    // Admin->modules
    Route::get('modules', 'ModuleController@index');
    Route::get('modules/create', 'ModuleController@create');
    Route::post('modules/create', 'ModuleController@store');
    Route::get('modules/{id}/edit', 'ModuleController@edit');
    Route::post('modules/{id}/edit', 'ModuleController@update');
    Route::get('modules/{id}/delete', 'ModuleController@delete');

    // Admin->courses
    Route::get('courses', 'CourseController@index');
    Route::get('courses/create', 'CourseController@create');
    Route::post('courses/create', 'CourseController@store');
    Route::get('courses/{id}/edit', 'CourseController@edit');
    Route::post('courses/{id}/edit', 'CourseController@update');
    Route::get('courses/{id}/delete', 'CourseController@delete');
    // Admin->workload
    Route::get('workload', 'WorkloadController@index');
    Route::get('workload/create', 'WorkloadController@create');
    Route::post('workload/create', 'WorkloadController@store');
    Route::get('workload/{id}/edit', 'WorkloadController@edit');
    Route::post('workload/{id}/edit', 'WorkloadController@update');
    Route::get('workload/{id}/delete', 'WorkloadController@delete');
    // Admin->enrollment
    Route::get('enrollments', 'EnrollmentController@index');
    Route::get('enrollments/create', 'EnrollmentController@create');
    Route::post('enrollments/create', 'EnrollmentController@store');
    Route::get('enrollments/{id}/edit', 'EnrollmentController@edit');
    Route::post('enrollments/{id}/edit', 'EnrollmentController@update');
    Route::get('enrollments/{id}/delete', 'EnrollmentController@delete');

    Route::group(['namespace' => 'Reports','prefix' => 'reports'], function (){
        Route::get('enrollments', 'EnrollmentController@index');
    });

    Route::get('graphics', 'GraphicController@index');
});

Route::group(['middleware' => ['auth','teacher'], 'namespace' => 'Admin', 'prefix' => 'admin'], function () {
    // teacher->assistance
    Route::get('/assistances', 'AssistanceController@index');
    Route::get('/assistances/create', 'AssistanceController@create');
    Route::post('/assistances/create', 'AssistanceController@store');
    Route::get('/assistances/{id}/edit', 'AssistanceController@edit');
    Route::post('/assistances/{id}/edit', 'AssistanceController@update');
    Route::get('/assistances/{id}/delete', 'AssistanceController@delete');
    // teacher->notes
    Route::get('/notes', 'NoteController@index');
    Route::get('/notes/create', 'NoteController@create');
    Route::post('/notes/create', 'NoteController@store');
    Route::get('/notes/{id}/edit', 'NoteController@edit');
    Route::post('/notes/{id}/edit', 'NoteController@update');
    Route::get('/notes/{id}/delete', 'NoteController@delete');
    Route::group(['namespace' => 'Reports','prefix' => 'reports'], function (){
        Route::get('assistances', 'AssistanceController@index');
        Route::get('notes', 'NoteController@index');
    });
});

app/Enrollment.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Enrollment extends Model
{
    use SoftDeletes;

    public function postulant()
    {
        return $this->belongsTo(User::class, 'postulant_id');
    }

    public function semester()
    {
        return $this->belongsTo(Semester::class);
    }

    public function career()
    {
        return $this->belongsTo(Career::class);
    }
}

app/Semester.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Semester extends Model
{
    public function enrollments()
    {
        return $this->hasMany(Enrollment::class);
    }

    public function getStartFormatAttribute()
    {
        return date('d/m/Y', strtotime($this->start_date));
    }

    public function getEndFormatAttribute()
    {
        return date('d/m/Y', strtotime($this->end_date));
    }

    public function getYearPeriodAttribute()
    {
        return $this->year.' - '.$this->period;
    }
}

app/Http/Controllers/Admin/EnrollmentController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Career;
use App\Enrollment;
use App\Semester;
use App\User;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Validator;

class EnrollmentController extends Controller
{
    public function index(Request $request)
    {
        $query = Enrollment::with('postulant');
        $searchEnrollment = $request->search_enrollment;

        if ($searchEnrollment) {// when search by date
            $query = $query->whereHas('postulant', function($query) use($searchEnrollment) {
                    $query->where('dni','LIKE', '%'.$searchEnrollment.'%')
                        ->orWhere('last_name','LIKE', '%'.$searchEnrollment.'%')
                        ->orderBy('id', 'desc');
                });
        }

        $enrollments = $query->get();

        return view('admin.enrollment.index', compact('enrollments', 'searchEnrollment'));
    }

    public function create()
    {
        $semesters = Semester::all();
        $careers = Career::all();

        if (old('postulant_id')) {
            $postulant = User::find(old('postulant_id'));
        }

        return view('admin.enrollment.create', compact('semesters','careers','postulant'));
    }

    public function store(Request $request)
    {
        $rules = [
            'postulant_id' => 'required',
            'career_id' => 'required',
            'semester_id' => 'required',
            'cycle' => 'required',
            'payment' => 'required|numeric|min:1'
        ];

        $messages = [
            'postulant_id.required' => 'Es necesario seleccionar un postulante.',
            'career_id.required' => 'Es necesario seleccionar la carrera.',
            'semester_id.required' => 'Es necesario seleccionar el semestre.',
            'cycle.required' => 'Es necesrio seleccionar el ciclo.',
            'payment.required' => 'Es necesario ingresar el pago.'
        ];

        $validator = Validator::make($request->all(), $rules, $messages);
        $validator->after(function($validator) use ($request) {
            $existsUser = Enrollment::where('postulant_id', $request->postulant_id)->where('semester_id', $request->semester_id)->exists();
            if ($existsUser)
                $validator->errors()->add('postulant_id', 'El postulante seleccionado ya tiene registrado una carrera.');
        });
        if ($validator->fails())
            return back()->withErrors($validator->messages())->withInput();

        //code
        $postulantId = $request->postulant_id;
        $careerId = $request->career_id;
        $semesterId = $request->semester_id;

        // new enrollment
        $enrollment = new Enrollment();
        $enrollment->code = $this->createCode($careerId, $semesterId);
        $enrollment->postulant_id = $postulantId;
        $enrollment->career_id = $careerId;
        $enrollment->semester_id = $semesterId;
        $enrollment->cycle = $request->cycle;
        $enrollment->payment = $request->payment;
        $enrollment->save();

        $notification = 'Se registró correctamente la matrícula.';
        return redirect('/admin/enrollments')->with(compact('notification'));
    }

    public function edit($id)
    {
        $enrollment = Enrollment::findOrFail($id);
        $semesters = Semester::all();
        $careers = Career::all();

        return view('admin.enrollment.edit', compact('enrollment', 'semesters', 'careers'));
    }

    public function update($id, Request $request)
    {
        $rules = [
            'postulant_id' => 'required',
            'career_id' => 'required',
            'semester_id' => 'required',
            'cycle' => 'required',
            'payment' => 'required|numeric|min:1'
        ];

        $messages = [
            'postulant_id.required' => 'Es necesario seleccionar un postulante.',
            'career_id.required' => 'Es necesario seleccionar la carrera.',
            'semester_id.required' => 'Es necesario seleccionar el semestre.',
            'cycle.required' => 'Es necesrio seleccionar el ciclo.',
            'payment.required' => 'Es necesario ingresar el pago.'
        ];

        $validator = Validator::make($request->all(), $rules, $messages);


        $validator->after(function($validator) use ($request, $id) {
            $existsUser = Enrollment::where('id', '<>', $id)->where('postulant_id', $request->postulant_id)->where('semester_id', $request->semester_id)->exists();
            if ($existsUser)
                $validator->errors()->add('postulant_id', 'El postulante seleccionado ya tiene registrado una carrera.');
        });
        if ($validator->fails())
            return back()->withErrors($validator->messages())->withInput();

        // new enrollment
        $enrollment = Enrollment::findOrFail($id);
        $enrollment->postulant_id = $request->postulant_id;
        $enrollment->career_id = $request->career_id;
        $enrollment->semester_id = $request->semester_id;
        $enrollment->cycle = $request->cycle;
        $enrollment->payment = $request->payment;
        $enrollment->save();

        $notification = 'Se guardaron los cambios correctamente.';
        return redirect('/admin/enrollments')->with(compact('notification'));
    }

    public function delete($id)
    {
        $enrollment = Enrollment::findOrFail($id);
        $enrollment->delete();

        return back()->with('notification', 'Se desactivó correctamente.');
    }

    public function createCode($careerId, $semesterId)
    {
        $semester = Semester::findOrFail($semesterId);
        $career = Career::findOrFail($careerId);

        $count = Enrollment::where('career_id', $careerId)->where('semester_id', $semesterId)->count()+1;
        $initialCareer = strtoupper(substr($career->name, 0, 3));
        $number = $semester->period == 'I' ? '1':'2';
        $period = $semester->year .'0'. $number;
        $order = str_pad($count, 3, "0", STR_PAD_LEFT);

        return $initialCareer.$period.'-'.$order;
    }
}

app/Http/Controllers/Admin/Reports/EnrollmentController.php
<?php

namespace App\Http\Controllers\Admin\Reports;

use App\Career;
use App\Enrollment;
use App\Semester;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Response;
use Illuminate\Support\Collection;

class EnrollmentController extends Controller
{
    public function index(Request $request)
    {
        $careerId = $request->career_id;
        $semesterId = $request->semester_id;
        $download = $request->download;

        $careers = Career::all();
        $semesters = Semester::all();
        $query = Enrollment::query();

        if ($careerId) {
            $query = $query->where('career_id', $careerId);
        }
        if ($semesterId) {
            $query = $query->where('semester_id', $semesterId);
        }

        if ($download){
            $data = $query->get();
            $table = (new Collection($data));
            $fileName = "reporte_matriculados.csv";
            $filePath = storage_path($fileName);
            $handle = fopen($filePath, 'w');
            fprintf($handle, chr(0xEF).chr(0xBB).chr(0xBF));
            fputcsv($handle, [
                'CÓDIGO', 'DNI', 'ALUMNO', 'CARRERA'
            ],";");
            foreach($table as $enrollment) {
                fputcsv($handle, [
                    $enrollment->postulant->code,
                    $enrollment->postulant->dni,
                    $enrollment->postulant->name_complete,
                    $enrollment->career->name,
                ],";");
            }
            fclose($handle);
            $headers = [
                'Content-Type' => 'text/csv',
            ];
            return Response::download($filePath, $fileName, $headers);
        }

        $enrollments = $query->paginate(10);

        return view('admin.reports.enrollments', compact('enrollments', 'careers', 'semesters', 'careerId', 'semesterId'));
    }
}

resources/views/admin/enrollment/create.blade.php
@extends('layouts.app')

@section('page-title')
    <a href="{{ url('/admin/enrollment') }}">Matrículas</a> >
    Nuevo
@endsection
@section('styles')
    <link href="{{ asset('plugins/select2/dist/css/select2.css') }}" rel="stylesheet" type="text/css">
    <link href="{{ asset('plugins/select2/dist/css/select2-bootstrap.css') }}" rel="stylesheet" type="text/css">
@endsection
@section('content')
    <div class="content">
        <div class="container">
            @if (session('notification'))
                <div class="alert alert-info alert-dismissable">
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                    {{ session('notification') }}
                </div>
            @endif

            @if ($errors->any())
                <div class="alert alert-danger">
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
            @endif

            <form role="form"  action="" method="POST">
                @csrf
                <div class="row">
                    <div class="col-sm-6">
                        <div class="card-box">
                            <h4 class="m-t-0 header-title m-t-0 m-b-20"><b>Datos de la Matrícula</b></h4>
                            <div class="form-group">
                                <label for="postulant_id">Postulante</label>
                                <input type="hidden" name="postulant_id" class="select2 form-control" id="postulant_id">
                            </div>
                            <div class="form-group">
                                <label for="career_id" class="control-label">Carrera</label>
                                <select class="form-control" id="career_id" name="career_id">
                                    <option value="">Seleccione carrera</option>
                                    @foreach($careers as $career)
                                        <option value="{{ $career->id }}" {{ old('career_id') == $career->id ? 'selected' : '' }}>{{ $career->name }}</option>
                                    @endforeach
                                </select>
                            </div>
                            <div class="row">
                                <div class="col-sm-6">
                                    <div class="form-group">
                                        <label for="semester_id" class="control-label">Semestre</label>
                                        <select class="form-control" id="semester_id" name="semester_id">
                                            <option value="">Seleccione semestre</option>
                                            @foreach($semesters as $semester)
                                                <option value="{{ $semester->id }}" {{ old('semester_id') == $semester->id ? 'selected' : '' }}>{{ $semester->year_period }}</option>
                                            @endforeach
                                        </select>
                                    </div>
                                </div>
                                <div class="col-sm-6">
                                    <div class="form-group">
                                        <label for="cycle" class="control-label">Ciclo</label>
                                        <select class="form-control" id="cycle" name="cycle">
                                            <option value="">Seleccione ciclo</option>
                                            <option value="I" {{ old('cycle') == 'I' ? 'selected' : '' }}>I</option>
                                            <option value="II" {{ old('cycle') == 'II' ? 'selected' : '' }}>II</option>
                                            <option value="III" {{ old('cycle') == 'III' ? 'selected' : '' }}>III</option>
                                            <option value="IV" {{ old('cycle') == 'IV' ? 'selected' : '' }}>IV</option>
                                            <option value="V" {{ old('cycle') == 'V' ? 'selected' : '' }}>V</option>
                                            <option value="VI" {{ old('cycle') == 'VI' ? 'selected' : '' }}>VI</option>
                                        </select>
                                    </div>
                                </div>
                                <div class="col-sm-6">
                                    <div class="form-group">
                                        <label for="payment" class="control-label">Pago</label>
                                        <input type="text" placeholder="" class="form-control" id="payment" name="payment" value="{{ old('payment') }}" onkeypress="return justNumbers(event);">
                                    </div>
                                </div>
                                {{--<div class="col-sm-6">--}}
                                    {{--<div class="form-group">--}}
                                        {{--<label for="cycle" class="control-label">Cursos</label>--}}
                                        {{--<a href="#" class="form-control btn btn-default btn-bordred">--}}
                                            {{--<i class="fa fa-list-alt"></i>--}}
                                        {{--</a>--}}
                                    {{--</div>--}}
                                {{--</div>--}}
                            </div>
                            <div class="form-group" >
                                <button class="btn btn-primary btn-bordred m-t-15">
                                    Registrar
                                    <i class="fa fa-save"></i>
                                </button>
                                <a href="{{ url('admin/enrollments') }}" class="btn btn-default btn-bordred m-l-5 m-t-15">
                                    Cancelar
                                </a>
                            </div>
                        </div><!-- end row -->
                    </div>
                </div><!-- end col -->
                <!-- end row -->
            </form>
        </div> <!-- container -->
    </div> <!-- content -->
@endsection
@section('scripts')
    <script>
        function justNumbers(e)
        {
            var keynum = window.event ? window.event.keyCode : e.which;
            if (keynum === 8 || keynum === 46)
                return true;
            return /\d/.test(String.fromCharCode(keynum));
        }
    </script>
    <script src="{{ asset('plugins/select2/dist/js/select2.min.js') }}" type="text/javascript"></script>
    <script>
        $('#postulant_id').select2({
            placeholder: 'Busque por nombre y apellidos...',
            ajax: {
                url: '/api/postulants',
                dataType: 'json',
                delay: 250,

                data: function (query) {
                    return {
                        queryText: query
                    };
                },

                results: function (data) {
                    return {
                        results: data
                    };
                },

                cache: true
            }
        });
        @if (old('postulant_id'))
        $('#postulant_id').select2('data', {id:{{$postulant->id}}, text:'{{$postulant->name_complete}}'});
        @endif
    </script>
@endsection

resources/views/admin/enrollment/edit.blade.php
@extends('layouts.app')

@section('page-title')
    <a href="{{ url('/admin/enrollment') }}">Matrículas</a> >
    Nuevo
@endsection
@section('styles')
    <link href="{{ asset('plugins/select2/dist/css/select2.css') }}" rel="stylesheet" type="text/css">
    <link href="{{ asset('plugins/select2/dist/css/select2-bootstrap.css') }}" rel="stylesheet" type="text/css">
@endsection
@section('content')
    <div class="content">
        <div class="container">
            @if (session('notification'))
                <div class="alert alert-info alert-dismissable">
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                    {{ session('notification') }}
                </div>
            @endif

            @if ($errors->any())
                <div class="alert alert-danger">
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
            @endif

            <form role="form"  action="" method="POST">
                @csrf
                <div class="row">
                    <div class="col-sm-6">
                        <div class="card-box">
                            <h4 class="m-t-0 header-title m-t-0 m-b-20"><b>Datos de la Matrícula</b></h4>
                            <div class="form-group">
                                <label for="payment" class="control-label">Código</label>
                                <input type="text" class="form-control"
                                       value="{{ $enrollment->code }}" disabled>
                            </div>
                            <div class="clearfix"></div>
                            <div class="form-group">
                                <label for="postulant_id">Postulante</label>
                                <input type="hidden" name="postulant_id" class="select2 form-control" id="postulant_id">
                            </div>
                            <div class="form-group">
                                <label for="career_id" class="control-label">Carrera</label>
                                <select class="form-control" id="career_id" name="career_id">
                                    <option value="">Seleccione carrera</option>
                                    @foreach($careers as $career)
                                        <option value="{{ $career->id }}" {{ old('career_id', $enrollment->career_id) == $career->id ? 'selected' : '' }}>{{ $career->name }}</option>
                                    @endforeach
                                </select>
                            </div>
                            <div class="row">
                                <div class="col-sm-6">
                                    <div class="form-group">
                                        <label for="semester_id" class="control-label">Semestre</label>
                                        <select class="form-control" id="semester_id" name="semester_id">
                                            <option value="">Seleccione semestre</option>
                                            @foreach($semesters as $semester)
                                                <option value="{{ $semester->id }}" {{ old('semester_id', $enrollment->semester_id) == $semester->id ? 'selected' : '' }}>{{ $semester->year_period }}</option>
                                            @endforeach
                                        </select>
                                    </div>
                                </div>
                                <div class="col-sm-6">
                                    <div class="form-group">
                                        <label for="cycle" class="control-label">Ciclo</label>
                                        <select class="form-control" id="cycle" name="cycle">
                                            <option value="">Seleccione ciclo</option>
                                            <option value="I" {{ old('cycle', $enrollment->cycle) == 'I' ? 'selected' : '' }}>I</option>
                                            <option value="II" {{ old('cycle', $enrollment->cycle) == 'II' ? 'selected' : '' }}>II</option>
                                            <option value="III" {{ old('cycle', $enrollment->cycle) == 'III' ? 'selected' : '' }}>III</option>
                                            <option value="IV" {{ old('cycle', $enrollment->cycle) == 'IV' ? 'selected' : '' }}>IV</option>
                                            <option value="V" {{ old('cycle', $enrollment->cycle) == 'V' ? 'selected' : '' }}>V</option>
                                            <option value="VI" {{ old('cycle', $enrollment->cycle) == 'VI' ? 'selected' : '' }}>VI</option>
                                        </select>
                                    </div>
                                </div>
                                <div class="col-sm-6">
                                    <div class="form-group">
                                        <label for="payment" class="control-label">Pago</label>
                                        <input type="text" placeholder="" class="form-control" id="payment" name="payment"
                                               value="{{ old('payment', $enrollment->payment) }}" onkeypress="return justNumbers(event);">
                                    </div>
                                </div>
                            </div>
                            <div class="form-group">
                                <button class="btn btn-success btn-bordred m-t-15">
                                    Guardar cambios
                                </button>
                                <a href="{{ url('admin/enrollments') }}" class="btn btn-default btn-bordred m-l-5 m-t-15">
                                    Cancelar
                                </a>
                            </div>
                        </div><!-- end row -->
                    </div>
                </div><!-- end col -->
                <!-- end row -->
            </form>
        </div> <!-- container -->
    </div> <!-- content -->
@endsection
@section('scripts')
    <script>
        function justNumbers(e)
        {
            var keynum = window.event ? window.event.keyCode : e.which;
            if (keynum === 8 || keynum === 46)
                return true;
            return /\d/.test(String.fromCharCode(keynum));
        }
    </script>
    <script src="{{ asset('plugins/select2/dist/js/select2.min.js') }}" type="text/javascript"></script>
    <script>
        $('#postulant_id').select2({
            placeholder: 'Busque por nombre y apellidos...',
            ajax: {
                url: '/api/postulants',
                dataType: 'json',
                delay: 250,

                data: function (query) {
                    return {
                        queryText: query
                    };
                },

                results: function (data) {
                    return {
                        results: data
                    };
                },
                cache: true
            }
        });
        $('#postulant_id').select2('data', {id:{{$enrollment->postulant->id}}, text:'{{$enrollment->postulant->name_complete}}'});
    </script>
@endsection