routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect('login');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

// namespace -> Admin
Route::group(['middleware' => ['auth','secretary'], 'namespace' => 'Admin', 'prefix' => 'admin'], function (){
    // Admin->teachers
    Route::get('teachers', 'TeacherController@index');
    Route::get('teachers/create', 'TeacherController@create');
    Route::post('teachers/create', 'TeacherController@store');
    Route::get('teachers/{id}/edit', 'TeacherController@edit');
    Route::post('teachers/{id}/edit', 'TeacherController@update');
    Route::get('teachers/{id}/delete', 'TeacherController@delete');
    // Admin->postulants
    Route::get('postulants', 'PostulantController@index');
    Route::get('postulants/create', 'PostulantController@create');
    Route::post('postulants/create', 'PostulantController@store');
    Route::get('postulants/{id}/edit', 'PostulantController@edit');
    Route::post('postulants/{id}/edit', 'PostulantController@update');
    Route::get('postulants/{id}/delete', 'PostulantController@delete');
    // Admin->semesters
    Route::get('semesters', 'SemesterController@index');
    Route::get('semesters/create', 'SemesterController@create');
    Route::post('semesters/create', 'SemesterController@store');
    Route::get('semesters/{id}/edit', 'SemesterController@edit');
    Route::post('semesters/{id}/edit', 'SemesterController@update');
    Route::get('semesters/{id}/delete', 'SemesterController@delete');
    // Admin->careers
    Route::get('careers', 'CareerController@index');
    Route::get('careers/create', 'CareerController@create');
    Route::post('careers/create', 'CareerController@store');
    Route::get('careers/{id}/edit', 'CareerController@edit');
    Route::post('careers/{id}/edit', 'CareerController@update');
    Route::get('careers/{id}/delete', 'CareerController@delete');
    Route::get('careers/{id}/modules', 'CareerController@modules');

    // Admin->modules
    Route::get('modules', 'ModuleController@index');
    Route::get('modules/create', 'ModuleController@create');
    Route::post('modules/create', 'ModuleController@store');
    Route::get('modules/{id}/edit', 'ModuleController@edit');
    Route::post('modules/{id}/edit', 'ModuleController@update');
    Route::get('modules/{id}/delete', 'ModuleController@delete');

    // Admin->courses
    Route::get('courses', 'CourseController@index');
    Route::get('courses/create', 'CourseController@create');
    Route::post('courses/create', 'CourseController@store');
    Route::get('courses/{id}/edit', 'CourseController@edit');
    Route::post('courses/{id}/edit', 'CourseController@update');
    Route::get('courses/{id}/delete', 'CourseController@delete');
    // Admin->workload
    Route::get('workload', 'WorkloadController@index');
    Route::get('workload/create', 'WorkloadController@create');
    Route::post('workload/create', 'WorkloadController@store');
    Route::get('workload/{id}/edit', 'WorkloadController@edit');
    Route::post('workload/{id}/edit', 'WorkloadController@update');
    Route::get('workload/{id}/delete', 'WorkloadController@delete');
    // Admin->enrollment
    Route::get('enrollments', 'EnrollmentController@index');
    Route::get('enrollments/create', 'EnrollmentController@create');
    Route::post('enrollments/create', 'EnrollmentController@store');
    Route::get('enrollments/{id}/edit', 'EnrollmentController@edit');
    Route::post('enrollments/{id}/edit', 'EnrollmentController@update');
    Route::get('enrollments/{id}/delete', 'EnrollmentController@delete');

    Route::group(['namespace' => 'Reports','prefix' => 'reports'], function (){
        Route::get('enrollments', 'EnrollmentController@index');
    });

    Route::get('graphics', 'GraphicController@index');
});

Route::group(['middleware' => ['auth','teacher'], 'namespace' => 'Admin', 'prefix' => 'admin'], function () {
    // teacher->assistance
    Route::get('/assistances', 'AssistanceController@index');
    Route::get('/assistances/create', 'AssistanceController@create');
    Route::post('/assistances/create', 'AssistanceController@store');
    Route::get('/assistances/{id}/edit', 'AssistanceController@edit');
    Route::post('/assistances/{id}/edit', 'AssistanceController@update');
    Route::get('/assistances/{id}/delete', 'AssistanceController@delete');
    // teacher->notes
    Route::get('/notes', 'NoteController@index');
    Route::get('/notes/create', 'NoteController@create');
    Route::post('/notes/create', 'NoteController@store');
    Route::get('/notes/{id}/edit', 'NoteController@edit');
    Route::post('/notes/{id}/edit', 'NoteController@update');
    Route::get('/notes/{id}/delete', 'NoteController@delete');
    Route::group(['namespace' => 'Reports','prefix' => 'reports'], function (){
        Route::get('assistances', 'AssistanceController@index');
        Route::get('notes', 'NoteController@index');
    });
});

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    protected $fillable = [
        'first_name', 'last_name', 'email', 'password', 'role',
    ];
    protected $hidden = [
        'password', 'remember_token',
    ];

    protected  $appends = ['name_complete', 'code'];

    //relationship
    public function career()
    {
        return $this->belongsTo(Career::class);
    }

    public function workload_careers()
    {
        return $this->belongsToMany(Career::class, 'workloads', 'teacher_id', 'career_id')->distinct('id');

    }

    public function assistances()
    {
        return $this->hasMany(Assistance::class);
    }

    public function enrollments()
    {
        return $this->hasMany(Enrollment::class, 'postulant_id');
    }

    public function notes()
    {
        return $this->hasMany(Note::class);
    }

    //accessors
    public function getGenderNameAttribute() // accessor gender_name
    {
        if ($this->gender == 'M')
            return 'Masculino';
        if ($this->gender == 'F')
            return 'Femenino';

        return ''; // ?
    }

    public function getImageUrlAttribute()
    {
        if($this->image)
            return '/images/users/'.$this->image;
        else
            return '/images/users/avatar-1.jpg';
    }

    public function getIsAdminAttribute()
    {
        return $this->role == 0 || $this->role == 1;
    }

    public function getIsSecretaryAttribute()
    {
        return $this->role == 2;
    }

    public function getIsTeacherAttribute()
    {
        return $this->role == 3;
    }

    public function getNameCompleteAttribute()
    {
        return $this->first_name.' '.$this->last_name;
    }

    public  function getCodeAttribute()
    {
        $firstEnrollment = $this->enrollments()->first();
        if ($firstEnrollment)
            return $firstEnrollment->code;

        return null;
    }
}

resources/views/includes/alerts.blade.php
@if (session('notification'))
    <div class="alert alert-info alert-dismissable">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
        {{ session('notification') }}
    </div>
@endif

@if ($errors->any())
    <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif

resources/views/includes/menu.blade.php
<div id="sidebar-menu">
    <ul>
        <li class="text-muted menu-title">Menú</li>
        <li>
            <a href="/home" class="waves-effect"><i class="zmdi zmdi-home"></i> <span>Inicio</span></a>
        </li>
        @if(auth()->user()->is_admin || auth()->user()->is_secretary)
        <li class="has_sub">
            <a href="javascript:void(0);" class="waves-effect"><i class="zmdi zmdi-collection-text"></i> <span> Datos generales </span> <span class="menu-arrow"></span></a>
            <ul class="list-unstyled">
                <li><a href="{{ asset('admin/teachers') }}">Docente</a></li>
                <li><a href="{{ asset('admin/postulants') }}">Postulante</a></li>
                <li><a href="{{ asset('admin/semesters') }}">Semestre</a></li>
                <li><a href="{{ asset('admin/careers') }}">Carrera</a></li>
                <li><a href="{{ asset('admin/modules') }}">Módulo</a></li>
                <li><a href="{{ asset('admin/courses') }}">Curso</a></li>
            </ul>
        </li>
        @endif
        <li class="has_sub">
            <a href="javascript:void(0);" class="waves-effect"><i class="zmdi zmdi-edit"></i> <span> Registros </span> <span class="menu-arrow"></span></a>
            <ul class="list-unstyled">
                @if(auth()->user()->is_secretary || auth()->user()->is_admin)
                    <li><a href="{{ url('admin/workload') }}">Carga Lectiva</a></li>
                    <li><a href="{{ url('admin/enrollments') }}">Matrícula</a>
                @endif
                @if(auth()->user()->is_teacher)
                    <li><a href="{{ url('admin/assistances') }}">Asistencias</a></li>
                    <li><a href="{{ url('admin/notes') }}">Notas</a></li>
                @endif
            </ul>
        </li>

        <li class="has_sub">
            <a href="javascript:void(0);" class="waves-effect"><i class="zmdi zmdi-chart"></i> <span> Reportes </span> <span class="menu-arrow"></span></a>
            <ul class="list-unstyled">
                {{--<li><a href="#">Postulantes</a></li>--}}
                @if(auth()->user()->is_admin || auth()->user()->is_secreatry)
                <li><a href="{{ url('admin/reports/enrollments') }}">Matriculados</a></li>
                @endif
                {{--<li><a href="#">Docentes</a></li>--}}
                @if(auth()->user()->is_teacher || auth()->user()->is_admin || auth()->user()->is_secreatry)
                    <li><a href="{{ url('admin/reports/assistances') }}">Asistencia</a></li>
                    <li><a href="{{ url('admin/reports/notes') }}">Notas</a></li>
                @endif
            </ul>
        </li>
        @if(auth()->user()->is_admin)
        <li>
            <a href="{{ url('admin/graphics') }}" class="waves-effect"><i class="fa fa-pie-chart"></i> <span>Gráficos</span></a>
        </li>
        @endif
    </ul>
    <div class="clearfix"></div>
</div>