routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect('login');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

// namespace -> Admin
Route::group(['middleware' => ['auth','secretary'], 'namespace' => 'Admin', 'prefix' => 'admin'], function (){
    // Admin->teachers
    Route::get('teachers', 'TeacherController@index');
    Route::get('teachers/create', 'TeacherController@create');
    Route::post('teachers/create', 'TeacherController@store');
    Route::get('teachers/{id}/edit', 'TeacherController@edit');
    Route::post('teachers/{id}/edit', 'TeacherController@update');
    Route::get('teachers/{id}/delete', 'TeacherController@delete');
    // Admin->postulants
    Route::get('postulants', 'PostulantController@index');
    Route::get('postulants/create', 'PostulantController@create');
    Route::post('postulants/create', 'PostulantController@store');
    Route::get('postulants/{id}/edit', 'PostulantController@edit');
    Route::post('postulants/{id}/edit', 'PostulantController@update');
    Route::get('postulants/{id}/delete', 'PostulantController@delete');
    // Admin->semesters
    Route::get('semesters', 'SemesterController@index');
    Route::get('semesters/create', 'SemesterController@create');
    Route::post('semesters/create', 'SemesterController@store');
    Route::get('semesters/{id}/edit', 'SemesterController@edit');
    Route::post('semesters/{id}/edit', 'SemesterController@update');
    Route::get('semesters/{id}/delete', 'SemesterController@delete');
    // Admin->careers
    Route::get('careers', 'CareerController@index');
    Route::get('careers/create', 'CareerController@create');
    Route::post('careers/create', 'CareerController@store');
    Route::get('careers/{id}/edit', 'CareerController@edit');
    Route::post('careers/{id}/edit', 'CareerController@update');
    Route::get('careers/{id}/delete', 'CareerController@delete');
    Route::get('careers/{id}/modules', 'CareerController@modules');

    // Admin->modules
    Route::get('modules', 'ModuleController@index');
    Route::get('modules/create', 'ModuleController@create');
    Route::post('modules/create', 'ModuleController@store');
    Route::get('modules/{id}/edit', 'ModuleController@edit');
    Route::post('modules/{id}/edit', 'ModuleController@update');
    Route::get('modules/{id}/delete', 'ModuleController@delete');

    // Admin->courses
    Route::get('courses', 'CourseController@index');
    Route::get('courses/create', 'CourseController@create');
    Route::post('courses/create', 'CourseController@store');
    Route::get('courses/{id}/edit', 'CourseController@edit');
    Route::post('courses/{id}/edit', 'CourseController@update');
    Route::get('courses/{id}/delete', 'CourseController@delete');
    // Admin->workload
    Route::get('workload', 'WorkloadController@index');
    Route::get('workload/create', 'WorkloadController@create');
    Route::post('workload/create', 'WorkloadController@store');
    Route::get('workload/{id}/edit', 'WorkloadController@edit');
    Route::post('workload/{id}/edit', 'WorkloadController@update');
    Route::get('workload/{id}/delete', 'WorkloadController@delete');
    // Admin->enrollment
    Route::get('enrollments', 'EnrollmentController@index');
    Route::get('enrollments/create', 'EnrollmentController@create');
    Route::post('enrollments/create', 'EnrollmentController@store');
    Route::get('enrollments/{id}/edit', 'EnrollmentController@edit');
    Route::post('enrollments/{id}/edit', 'EnrollmentController@update');
    Route::get('enrollments/{id}/delete', 'EnrollmentController@delete');

    Route::group(['namespace' => 'Reports','prefix' => 'reports'], function (){
        Route::get('enrollments', 'EnrollmentController@index');
    });

    Route::get('graphics', 'GraphicController@index');
});

Route::group(['middleware' => ['auth','teacher'], 'namespace' => 'Admin', 'prefix' => 'admin'], function () {
    // teacher->assistance
    Route::get('/assistances', 'AssistanceController@index');
    Route::get('/assistances/create', 'AssistanceController@create');
    Route::post('/assistances/create', 'AssistanceController@store');
    Route::get('/assistances/{id}/edit', 'AssistanceController@edit');
    Route::post('/assistances/{id}/edit', 'AssistanceController@update');
    Route::get('/assistances/{id}/delete', 'AssistanceController@delete');
    // teacher->notes
    Route::get('/notes', 'NoteController@index');
    Route::get('/notes/create', 'NoteController@create');
    Route::post('/notes/create', 'NoteController@store');
    Route::get('/notes/{id}/edit', 'NoteController@edit');
    Route::post('/notes/{id}/edit', 'NoteController@update');
    Route::get('/notes/{id}/delete', 'NoteController@delete');
    Route::group(['namespace' => 'Reports','prefix' => 'reports'], function (){
        Route::get('assistances', 'AssistanceController@index');
        Route::get('notes', 'NoteController@index');
    });
});

app/Note.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Note extends Model
{
    public function career()
    {
        return $this->belongsTo(Career::class);
    }

    public function course()
    {
        return $this->belongsTo(Course::class);
    }

    public function details()
    {
        return $this->hasMany(NoteDetail::class, 'note_id');
    }


    public function getDateFormatAttribute()
    {
        return date('d/m/Y', strtotime($this->date));
    }
}

app/Http/Controllers/Admin/NoteController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Career;
use App\Enrollment;
use App\Note;
use App\NoteDetail;
use Carbon\Carbon;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class NoteController extends Controller
{
    public function index()
    {
        $user = auth()->user();

        $notes = $user->notes;

        return view('admin.notes.index', compact('notes'));
    }

    public function create()
    {
        $user = auth()->user();

        $careers = $user->workload_careers;
        if (old('career_id'))
            $oldCareer = Career::findOrFail(old('career_id'));


        return view('admin.notes.create', compact('user','careers', 'oldCareer'));
    }

    public function store(Request $request)
    {
        $note = new Note();
        $note->career_id = $request->career_id;
        $note->course_id = $request->course_id;
        $date = $request->date;
        $note->date = Carbon::createFromFormat('d/m/Y', $date);
        $note->user_id = auth()->id();
        $note->save();

        $enrollmentIds = $request->enrollmentIds;
        $notes1 = $request->notes1;
        $notes2 = $request->notes2;
        $notes3 = $request->notes3;
        $notes4 = $request->notes4;

        $course = $note->course;
        $evaluation = $course->evaluation_criteria;

        for ($i=0;$i<count($enrollmentIds);$i++) {
            $sum = 0;
            $notesOne = $notes1[$i] ? $notes1[$i] : 0;
            $notesTwo = $notes2[$i] ? $notes2[$i] : 0;
            $notesThree = $notes3[$i] ? $notes3[$i] : 0;
            $notesFour = $notes4[$i] ? $notes4[$i] : 0;

            $detail = new NoteDetail();
            if ($evaluation >= 1) {
                $detail->note_1 = $notesOne;
                $sum += $notesOne;
            }
            if ($evaluation >= 2) {
                $detail->note_2 = $notesTwo;
                $sum += $notesTwo;
            }
            if ($evaluation >= 3) {
                $detail->note_3 = $notesThree;
                $sum += $notesThree;
            }
            if ($evaluation >= 4) {
                $detail->note_4 = $notesFour;
                $sum += $notesFour;
            }
            $average = ($sum)/$evaluation;
            $detail->average = number_format($average, 2);
            $detail->enrollment_id = $enrollmentIds[$i];
            $detail->note_id = $note->id;
            $detail->save();
        }

        return redirect('admin/notes')->with('notification', 'Se registró correctamente');
    }

    public function edit($id)
    {
        $user = auth()->user();
        $careers = $user->workload_careers;
        $note = Note::findOrFail($id);
        $enrollments = Enrollment::with('postulant')->where('career_id', $note->career_id)
            ->where('cycle', $note->course->cycle)->get();
        if (old('career_id'))
            $oldCareer = Career::findOrFail(old('career_id'));

        return view('admin.notes.edit', compact('user','careers', 'oldCareer', 'note', 'enrollments'));
    }

    public function update($id, Request $request)
    {
        $note = Note::findOrFail($id);
        $note->career_id = $request->career_id;
        $note->course_id = $request->course_id;
        $date = $request->date;
        $note->date = Carbon::createFromFormat('d/m/Y', $date);
        $note->save();

        $enrollmentIds = $request->enrollmentIds;
        $notes1 = $request->notes1;
        $notes2 = $request->notes2;
        $notes3 = $request->notes3;
        $notes4 = $request->notes4;

        $note->details()->delete();

        $course = $note->course;
        $evaluation = $course->evaluation_criteria;

        for ($i=0;$i<count($enrollmentIds);$i++) {
            $sum = 0;
            $notesOne = isset($notes1[$i]) ? $notes1[$i] : 0;
            $notesTwo = isset($notes2[$i]) ? $notes2[$i] : 0;
            $notesThree = isset($notes3[$i]) ? $notes3[$i] : 0;
            $notesFour = isset($notes4[$i]) ? $notes4[$i] : 0;

            $detail = new NoteDetail();
            if ($evaluation >= 1) {
                $detail->note_1 = $notesOne;
                $sum += $notesOne;
            }
            if ($evaluation >= 2) {
                $detail->note_2 = $notesTwo;
                $sum += $notesTwo;
            }
            if ($evaluation >= 3) {
                $detail->note_3 = $notesThree;
                $sum += $notesThree;
            }
            if ($evaluation >= 4) {
                $detail->note_4 = $notesFour;
                $sum += $notesFour;
            }
            $average = ($sum)/$evaluation;
            $detail->average = number_format($average, 2);
            $detail->enrollment_id = $enrollmentIds[$i];
            $detail->note_id = $note->id;
            $detail->save();
        }

        return redirect('admin/notes')->with('notification', 'Se guardaron los cambios correctamente');
    }

    public function delete($id)
    {
        $note = Note::findOrFail($id);
        $note->details()->delete();
        $note->delete();

        return back()->with('notification', 'Se eliminó correctamente.');
    }
}

app/Http/Controllers/Admin/Reports/NoteController.php
<?php

namespace App\Http\Controllers\Admin\Reports;

use App\Career;
use App\Course;
use App\Enrollment;
use App\Note;
use App\NoteDetail;
use App\Semester;
use App\User;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Response;
use Illuminate\Support\Collection;

class NoteController extends Controller
{
    public function index(Request $request)
    {
        $filter = $request->filter;
        $postulantId = $request->postulant_id;
        $semesterId = $request->semester_id;
        $courseId = $request->course_id;
        $download = $request->download;

        $postulantIds = Enrollment::pluck('postulant_id');
        $postulants = User::whereIn('id', $postulantIds)->get();
        $semesters = Semester::all();
        $courseIds = Note::pluck('course_id');
        $courses = Course::whereIn('id', $courseIds)->orderBy('name')->get();

        $query = NoteDetail::with('enrollment');

        if ($postulantId) {
            $query = $query->whereHas('enrollment', function($query) use ($postulantId) {
                $query->where('postulant_id', $postulantId);
            });
        }
        if ($semesterId) {
            $query = $query->whereHas('enrollment', function($query) use ($semesterId) {
                $query->where('semester_id', $semesterId);
            });
        }

        if($courseId) {
            $noteIds = Note::where('course_id', $courseId)->pluck('id');
            $query = $query->whereIn('note_id', $noteIds);
        }


        if ($download){
            $data = $query->get();
            $table = (new Collection($data));
            $fileName = "reporte_notas.csv";
            $filePath = storage_path($fileName);
            $handle = fopen($filePath, 'w');
            fprintf($handle, chr(0xEF).chr(0xBB).chr(0xBF));
            fputcsv($handle, [
                'CÓDIGO', 'ALUMNO', 'CARRERA', 'CURSO', 'CE1', 'CE2', 'CE3', 'CE4', 'PROMEDIO'
            ],";");
            foreach($table as $detail) {
                fputcsv($handle, [
                    $detail->enrollment->postulant->code,
                    $detail->enrollment->postulant->name_complete,
                    $detail->enrollment->career->name,
                    $detail->note->course->name,
                    $detail->note_1,
                    $detail->note_2,
                    $detail->note_3,
                    $detail->note_4,
                    $detail->average
                ],";");
            }
            fclose($handle);
            $headers = [
                'Content-Type' => 'text/csv',
            ];
            return Response::download($filePath, $fileName, $headers);
        }

        $notes = $query->paginate(10);

        return view('admin.reports.notes', compact('notes', 'postulants', 'semesters', 'courses', 'postulantId', 'semesterId', 'courseId', 'filter'));
    }
}

resources/views/admin/notes/edit.blade.php
@extends('layouts.app')

@section('icon')
@endsection
@section('styles')
    <link href="{{ asset('plugins/timepicker/bootstrap-timepicker.min.css') }}" rel="stylesheet">
    <link href="{{ asset('plugins/bootstrap-datepicker/dist/css/bootstrap-datepicker.min.css') }}" rel="stylesheet">
@endsection

@section('page-title')
    Notas
@endsection

@section('content')
    <div class="content">
        <div class="container">
            @if (session('notification'))
                <div class="alert alert-info alert-dismissable">
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                    {{ session('notification') }}
                </div>
            @endif

            @if (count($errors) > 0)
                <div class="alert alert-danger">
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
            @endif
            <form action="" method="POST">
                @csrf
                <div class="card-box">
                    <div class="row">
                        <div class="col-sm-4">
                            <div class="form-group">
                                <label for="select_career" class="control-label">Carrera</label>
                                <select class="form-control" name="career_id" id="select_career" data-user-id="{{$user->id}}" required>
                                    <option value="">Seleccione Carrera</option>
                                    @foreach($careers as $career)
                                        <option value="{{ $career->id }}" {{ old('career_id', $note->career_id) == $career->id ? 'selected' : '' }}>{{ $career->name }}</option>
                                    @endforeach
                                </select>
                            </div>
                        </div><!-- end col -->
                        <div class="col-sm-4">
                            <div class="form-group">
                                <label for="select_course" class="control-label">Curso</label>
                                <select class="form-control" id="select_course" name="course_id" required>
                                    <option value="">Seleccione curso</option>
                                    @foreach($note->career->workload_courses as $course)
                                        <option value="{{ $course->id }}" {{ old('course_id', $note->course_id) == $course->id ? 'selected' : '' }}>{{ $course->name }}</option>
                                    @endforeach
                                </select>
                            </div>
                        </div><!-- end col -->
                        <div class="col-sm-4 m-b-10">
                            <div class="form-group">
                                <label class="control-label">Fecha</label>
                                <input type="text" class="form-control" name="date" id="datepicker-autoclose" value="{{ $note->date_format }}" required>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="card-box">
                    <h4 class="header-title m-t-0 m-b-30">Lista de matrículas</h4>
                    <div class="table-responsive">
                        <table class="table m-0">
                            <thead>
                            <tr id="headNotes">
                                <th class="col-sm-2">Código</th>
                                <th>Alumno</th>
                                <th>Ciclo</th>
                                @for($i=1;$i<=$note->course->evaluation_criteria;$i++)
                                    <th>CE {{$i}}</th>
                                @endfor
                                <th>Promedio</th>
                            </tr>
                            </thead>
                            <tbody id="contentNotes">
                                @foreach($note->details as $detail)
                                    <tr>
                                        <th id="code">{{ $detail->enrollment->postulant->code }}</th>
                                        <td id="name">{{ $detail->enrollment->postulant->name_complete }}</td>
                                        <td id="cycle">{{ $detail->enrollment->cycle }}</td>
                                        @if($detail->note_1 !== null)
                                            <td class="col-sm-1">
                                                <input type="number" class="form-control" min="0" max="20" id="note1{{ $detail->enrollment_id }}" name="notes1[]" value="{{ $detail->note_1 }}" onchange="getAverage({{$detail->enrollment_id}})">
                                            </td>
                                        @endif
                                        @if($detail->note_2 !== null)
                                            <td class="col-sm-1">
                                                <input type="number" class="form-control" min="0" max="20" id="note2{{ $detail->enrollment_id }}" name="notes2[]" value="{{ $detail->note_2 }}" onchange="getAverage({{ $detail->enrollment_id }})">
                                            </td>
                                        @endif
                                        @if($detail->note_3 !== null)
                                            <td class="col-sm-1">
                                                <input type="number" class="form-control" min="0" max="20" id="note3{{ $detail->enrollment_id }}" name="notes3[]" value="{{ $detail->note_3 }}" onchange="getAverage({{ $detail->enrollment_id }})">
                                            </td>
                                        @endif
                                        @if($detail->note_4 !== null)
                                            <td class="col-sm-1">
                                                <input type="number" class="form-control" min="0" max="20" id="note4{{ $detail->enrollment_id }}" name="notes4[]" value="{{ $detail->note_4 }}" onchange="getAverage({{ $detail->enrollment_id }})">
                                            </td>
                                        @endif
                                        <td class="col-sm-1">
                                            <input type="hidden" value="{{ $detail->enrollment_id }}" name="enrollmentIds[]">
                                            <input type="text" class="form-control" id="average{{ $detail->enrollment_id }}" value="{{ $detail->average }}" disabled>
                                        </td>
                                        </tr>
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                    <div id="errorMessage"></div>
                    <div class="form-group" >
                        <button class="btn btn-primary btn-bordred" id="btnRegister">
                            Guardar cambios
                        </button>
                        <a href="{{ url('admin/notes') }}" class="btn btn-default btn-bordred">Cancelar</a>
                    </div>
                </div>
            </form>
        </div>
    </div>
@endsection

@section('scripts')
    <script src="{{ asset('plugins/timepicker/bootstrap-timepicker.min.js') }}"></script>
    <script src="{{ asset('plugins/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js') }}"></script>
    <script>
        jQuery('#datepicker-autoclose').datepicker({
            autoclose: true,
            todayHighlight: true
        });
    </script>
    <script>
        $(function() {
            $('#select_career').on('change', onSelectCourseChange);
            $('#datepicker-autoclose, #select_course, #select_career').on('change', onShowPostulants);
        });
        var evaluation = {{ $note->course->evaluation_criteria }};
        function onSelectCourseChange() {
            var careerId = $(this).val();
            const userId = $(this).data('user-id');
            if (!careerId) {
                $('#select_course').html('<option value="">Seleccione curso</option>');
                $('#select_course').prop('disabled', true);
                return;
            }
            // AJAX
            $.get('/api/career/'+careerId+'/'+userId+'/courses', function (data) {
                var html_select = '<option value="">Seleccione curso</option>';
                for (var i=0; i<data.length; ++i)
                    html_select += '<option value="'+data[i].id+'">'+data[i].name+'</option>';
                $('#select_course').html(html_select);
                $('#select_course').prop('disabled', false);
            });
        }

        function onShowPostulants() {
            var careerId = $('#select_career').val();
            var courseId = $('#select_course').val();
            var $date = $('#datepicker-autoclose').val();
            const $content = $('#contentNotes');
            const $btnRegister = $('#btnRegister');
            const $message = $('#errorMessage');

            if (careerId && courseId && $date) {

                $content.append('<i class="fa fa-2x fa-spinner fa-spin"></i>');
                // AJAX
                $.get('/api/course/'+courseId, function (course) {
                    const $head = $('#headNotes');
                    $head.empty();
                    $head.append('<th class="col-sm-2">Código</th>\n' +
                        '<th>Alumno</th>\n' +
                        '<th>Ciclo</th>\n');
                    for($i=1;$i<=course.evaluation_criteria; $i++)
                        $head.append('<th>CE '+$i+'</th>\n');

                    $head.append('<th>Promedio</th>');

                    evaluation = course.evaluation_criteria;

                });
                // AJAX
                $.get('/api/postulants/'+careerId+'/'+courseId+'/?date='+$date, function (enrollments) {
                    $content.empty();
                    if (enrollments.length > 0) {
                        for (var i=0; i<enrollments.length; ++i) {
                            var enrollment = enrollments[i];
                            var $tr = $('<tr>');
                            $content.append($tr);

                            $tr.append('<th id="code">'+enrollment.postulant.code+'</th>\n' +
                                '<td id="name">'+enrollment.postulant.name_complete+'</td>\n' +
                                '<td id="cycle">'+enrollment.cycle+'</td>\n');

                            for($i=1;$i<=evaluation; $i++) {
                                $tr.append('<td class="col-sm-1">\n' +
                                    '<input type="number" class="form-control" min="0" max="20" step="any" id="note'+$i+enrollment.id+'" name="notes'+$i+'[]" value="0" onchange="getAverage('+enrollment.id+')">\n' +
                                    '</td>\n');
                            }

                            $tr.append('<td class="col-sm-1">' +
                                '<input type="hidden" value="'+enrollment.id+'" name="enrollmentIds[]">' +
                                '<input type="text" class="form-control" id="average'+enrollment.id+'" value="0" disabled>\n' +
                                '</td>\n' +
                                '</tr>');
                        }
                        $message.empty();
                        $btnRegister.show();
                    } else {
                        $message.html('No se encontraron alumnos inscritos a este curso');
                        $btnRegister.hide();
                    }
                });
            }
        }
    </script>
    <script>
        function getAverage(enrollmentId) {
            const $note1 = $('#note1'+enrollmentId);
            const $note2 = $('#note2'+enrollmentId);
            const $note3 = $('#note3'+enrollmentId);
            const $note4 = $('#note4'+enrollmentId);
            var $average = $('#average'+enrollmentId);

            var sum = 0;
            if(evaluation >= 4)
                sum += $note4.val() ? parseFloat($note4.val()) : 0;
            if(evaluation >= 3)
                sum += $note3.val() ? parseFloat($note3.val()) : 0;
            if(evaluation >= 2)
                sum += $note2.val() ? parseFloat($note2.val()) : 0;
            if(evaluation >= 1)
                sum += $note1.val() ? parseFloat($note1.val()) : 0;

            var average = ( sum ) / evaluation;

            $average.val(average.toFixed(2));
        }
    </script>
@endsection

resources/views/admin/notes/index.blade.php
@extends('layouts.app')

@section('icon')
@endsection

@section('page-title')
    Notas
@endsection

@section('content')
    <div class="content">
        <div class="container">
            @if (session('notification'))
                <div class="alert alert-info alert-dismissable">
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                    {{ session('notification') }}
                </div>
            @endif

            @if (count($errors) > 0)
                <div class="alert alert-danger">
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
            @endif
            <div class="row">
                <div class="col-sm-8">
                    <a href="{{ url('admin/notes/create') }}" class="btn btn-success btn-md waves-effect waves-light m-b-30"
                       data-overlaySpeed="200" data-overlayColor="#36404a">Registrar nueva nota</a>
                </div><!-- end col -->
            </div>
            <div class="row">
                <div class="col-lg-12">
                    <div class="card-box">
                        <h4 class="header-title m-t-0 m-b-30">Lista de notas</h4>
                        <div class="table-responsive">
                            <table class="table m-0">
                                <thead>
                                <tr>
                                    <th>#</th>
                                    <th>Carrera</th>
                                    <th>Curso</th>
                                    <th>Fecha</th>
                                    <th>Acciones</th>
                                </tr>
                                </thead>
                                <tbody>
                                @foreach($notes as $note)
                                    <tr>
                                        <th scope="row">{{ $note->id }}</th>
                                        <td>{{ $note->career->name }}</td>
                                        <td>{{ $note->course->name }}</td>
                                        <td>{{ $note->date_format }}</td>
                                        <td>
                                            <a href="{{ url('admin/notes/'.$note->id.'/edit') }}" class="btn btn-sm btn-primary" title="Editar">
                                                <i class="fa fa-pencil-square-o"></i>
                                            </a>
                                            <button class="btn btn-sm btn-danger" title="Eliminar" data-delete="{{ url('admin/notes/'.$note->id.'/delete') }}">
                                                <i class="fa fa-trash o"></i>
                                            </button>
                                        </td>
                                    </tr>
                                @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@section('scripts')
    <script>
        $(document).ready(function() {
            $('[data-delete]').on('click', onClickAssistanceDelete);
        });
        function onClickAssistanceDelete() {
            let urlDelete = $(this).data('delete');
            swal({
                title: '¿Seguro que desea eliminar esta nota?',
                text: "",
                type: 'warning',
                showCancelButton: true,
                confirmButtonColor: '#d33',

                cancelButtonText: 'Cancelar',
                confirmButtonText: 'Sí, eliminar!'
            }).then((result) => {
                if (result.value) {
                location.href = urlDelete;
            }
        });
        }
    </script>
@endsection